### ISSUE TITLE
Don't hardcode navbar

### ISSUE THREAD

**Issue by ausbin** [uniting-humanitarians/uh#62]
Suggestions:

- Add a `NavbarEntry` model to `ghu_main` with columns kinda like:
    - label
    - page
    - order
- I've used [django-ordered-model](https://pypi.python.org/pypi/django-ordered-model/) in the past for ordered rows, it's nice and gives you nice buttons in the admin
- Uncomment bootstrap navbar in `ghu_main/base.html` template in `ghu_main` and make it use navbar from database

Acceptance criteria:

 - [ ] Navbar is stored in database
 - [ ] Navbar entries editable, rearrangeable in Django admin
 - [ ] Navbar links to pages, not URLs (unless you think we might sometimes wanna link to URLs)

**Comment by S-reinken** [comment]
Due Date: Friday 9/22
