### ISSUE TITLE
Give Pages a description column, put in <meta description="XXX">

### ISSUE THREAD

**Issue by ausbin** [uniting-humanitarians/uh#82]
Right now, our result in Google looks like this:

![screenshot from 2017-09-22 09-40-14](https://user-images.githubusercontent.com/431756/30747237-936ba792-9f7a-11e7-87c4-9eb53a00cbcb.png)

The description there isn't very helpful. Google populates it from the page contents because we have no `<meta name="Description" content="...">` tag in the page. See: https://support.google.com/webmasters/answer/35624?hl=en#1

I think we should:

 - [ ] Add a **required** (i.e., `blank=False`) description field to the Page model (`ghu_web/ghu_main/models.py`)
 - [ ] Make a new migration (preferably named something nice if you do `python manage.py makemigrations -n nice-migration-name`)
 - [ ] Add a `description` block to `ghu_web/ghu_global/templates/ghu_global/layout.html`, like `<meta name="Description" content="{% block description %}some generic default description{% endblock %}">`
 - [ ] Then, in the Page template (`ghu_web/ghu_main/templates/ghu_main/page.html`), say `{% block description %}page.description{% endblock %}`.
 - [ ] Regenerate the `pages.json` [fixture](https://docs.djangoproject.com/en/1.11/howto/initial-data/): `./manage.py dumpdata ghu_main.Page >ghu_main/fixtures/pages.json`

**Comment by ausbin** [comment]
this isn't something we can really demo, so i'm gonna push it to sprint 3

**Comment by ausbin** [comment]
btw in case anyone cares, our pagerank is pretty not-so-heckin-good so to get us in results you need to search `site:globalhumanitariansunite.org` so something like:

https://google.com/search?q=site:globalhumanitariansunite.org
